spring:
  datasource:
    url: jdbc:mysql://localhost:3306/queswer?useUnicode=true&characterEncoding=utf8&useSSL=false&&serverTimezone=Asia/Shanghai
    username: root
    password: 数据库密码
    hikari:
      maximum-pool-size: 100
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    default-executor-type: REUSE
#resouerce
resourceLocation: /home/root/temp/img/
server:
  tomcat:
    basedir: /home/root/temp
  port: 8090