spring:
  datasource:
    url: jdbc:mysql://localhost:3306/queswer?useUnicode=true&characterEncoding=utf8&useSSL=false&&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      maximum-pool-size: 100
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    default-executor-type: REUSE
#resouerce
resourceLocation: D:/Personal/Desktop/project/img/
