spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_manager?useUnicode=true&characterEncoding=utf8&useSSL=false&&serverTimezone=Asia/Shanghai
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    default-executor-type: reuse
#resouerce
resourceLocation: D:/Personal/Desktop/project/img/
